---
################################################################
# node provision
################################################################
# 1. node features
# node_disable_numa: false        # [VERY IMPORTANT] disable numa, skip for vm or single CPU setup
# node_disable_swap: true         # [VERY IMPORTANT] disable swap for pg and kubernetes
# node_disable_firewall: true     # disable firewall to allow haproxy and kubernetes
# node_disable_selinux: true      # disable selinux
# node_disk_prefetch: false       # setup disk prefetch on HDD to increase performance

# 2. node kernel
# node_kernel_modules: [softdog, br_netfilter, ip_vs, ip_vs_rr, ip_vs_rr, ip_vs_wrr, ip_vs_sh, nf_conntrack_ipv4]

# 3. node tuned
# node_tuned: true                # tune node parameters
# node_sysctl_params: {}          # additional sysctl parameters

# 4. node user
# node_root_setup: false          # setup root user(ssh exchange) ?

# 5. node dns
node_dns_setup: true              # setup dns
node_static_dns:
  - host: 127.0.0.1               # loopback
    domain: [localhost, local, lc]
  - host: 10.10.10.10             # meta controller
    domain: [meta, pigsty, yum.pigsty]
#  # common nodes
#  - host: 10.10.10.10
#    domain: [node-0, n0]
#  - host: 10.10.10.11
#    domain: [node-1, n1]
#  - host: 10.10.10.12
#    domain: [node-2, n2]
#  - host: 10.10.10.13
#    domain: [node-3, n3]

node_dns_servers: [10.10.10.10] # default DNS server (meta node dnsmasq by default)

# 6. node repo
# node_local_repo_enabled: true     # whether use local yum repo
# node_local_repo_only: true        # whether disable other repos
# repo_name: pigsty                 # local repo name
# repo_host: yum.pigsty             # local repo host

# 7. node packages
# node_meta_install: false
# node_cloud_install: false
# node_build_install: false
# node_additional_packages: []   # additional rpm packages to be downloaded/installed

# 8. node ntp
node_setup_ntp: true            # setup ntp
node_timezone: 'Asia/Shanghai'  # default node timezone
node_ntp_servers: [10.10.10.10] # default NTP servers

# 9. node vip
node_setup_vip: true            # setup default vip structure

#==============================================================#
# dcs
#==============================================================#
dcs_type:    consul                  # default dcs server type: consul
dcs_servers: [10.10.10.10]           # default dcs servers
dcs_purge: true                      # force remove existing server
dcs_check_interval: 5s               # default service check interval
dcs_check_timeout:  1s               # default service check timeout


##==============================================================#
## cloud-native
##==============================================================#
## docker & k8s
#docker_cgroups_driver: systemd                                    # docker default cgroup fs driver
#docker_image_cache: /www/pigsty/docker-images.tar.lz4             # docker images cache path (.tar.lz4)
#docker_registry_mirrors: ["https://zbwt4y5v.mirror.aliyuncs.com"] # docker registry mirror
#k8s_registry_mirrors: registry.aliyuncs.com/google_containers     # kubernetes versionaliyun k8s miiror repository
#
#k8s_servers: [10.10.10.10]                                        # kubernetes servers (masters)
#k8s_version: 1.18.3                                               # kubernetes version
#k8s_pod_cidr: "10.11.0.0/16"                                      # kubernetes pod network cidr
#k8s_service_cidr: "10.12.0.0/16"                                  # kubernetes service network cidr
#k8s_dashboard_admin_user: dashboard-admin-sa                      # kubernetes dashboard admin user name
#k8s_role: node                                                  # overwrite this for master node


################################################################
# meta
################################################################
metadb_url: postgres://meta@pg-meta/meta
grafana_url: http://grafana.pigsty
prometheus_url: http://prometheus.pigsty/api
alertmanager_url: http://alertmanager.pigsty/api


################################################################
# PostgreSQL
################################################################

#==============================================================#
# Postgres Installation Options
#==============================================================#
# pg_version: 12                  # default postgresql version
# pg_postgis_version: 30          # install postgis extension?
# pg_pgdg_repo: false               # use official pgdg yum repo (disable if you have local mirror)
# pg_dbsu:  postgres               # postgresql dbsu (currently setup during node provision)
# pg_home:  /usr/pgsql             # postgresql binary
# pg_bin:   /usr/pgsql/bin         # postgresql binary
# pg_postgis_install: true        # install postgis extension?
# pg_extension_install: true      # install postgis extension?


#==============================================================#
# Postgres Initdb Options
#==============================================================#
# pg_cluster:                   # [REQUIRED] cluster name [VERY Important!]
#pg_data: /pg/data               # postgres data directory
#pg_port: 5432                   # postgres port
#pg_purge: false                 # force removing existing cluster ???!!! [DANGEROUS]
#pg_overwrite_hostname: true     # overwrite node hostname with pg instance name
#
#pg_standby_cluster: false       # if set to true, init this cluster as a standby cluster
#pg_initdb_method: initdb        # option: initdb  | backup | upstream
#                                #  * initdb:  create a new cluster
#                                #  * data:    use existing data dir (if version match)
#                                #  * backup:  extract a baebackup from file
#                                #  * pg_baesbackup: make online backup from upstream
#                                #  * standby_cluster: mark this cluster as standby cluster
#
#
## used when method=initdb : locale=C.UTF8 and enable datachecksum
#pg_initdb_opts: '--encoding=UTF8 --locale=C --data-checksum'
#pg_initdb_backup_path:          # used when method=backup : standard backup file path:
#pg_initdb_upstream_url:         # used when method=pg_basebackup|standby_cluster
#
#pg_listen_address: '*'          # postgres listen address, '*' by default
## postgresql_conf_path: "postgresql-{{ version }}.conf" # config path: if provided
#pg_primary_hba_path: "pg_hba-primary.conf"            # primary hba config file
#pg_replica_hba_path: "pg_hba-replica.conf"            # replica hba config file
#pg_archive_hba_path: "pg_hba-archive.conf"            # archive hba config file
#
## system user: replication and monitor (important!)
pg_replication_username: 'replicator'
pg_replication_password: 'replicator'
pg_monitor_username: 'dbuser_monitor'
pg_monitor_password: 'dbuser_monitor'

## pg scripts that modify template1 database
#pg_template_scripts:
#  - default-role.sql
#  - monitor-schema.sql

## default database and users ()
##pg_default_database: 'postgres'
##pg_default_username: 'postgres'
##pg_default_password: 'postgres'

#==============================================================#
# Pgbouncer Settings
#==============================================================#
#pg_pgbouncer_enabled: true                # default pooler
#pg_pgbouncer_port: 6432                   # default pgbouncer port
#pg_pgbouncer_poolmode: transaction        # default pooling mode: transaction pooling
#pg_pgbouncer_max_db_conn: 200             # important! do not set this larger than postgres max conn or conn limit

#==============================================================#
# Patroni Settings
#==============================================================#
#pg_patroni_enabled: true                  # default ha agent
#pg_patroni_port: 8008
#pg_patroni_watchdog: true                 # use watchdog?
#pg_patroni_watchdog_path: /dev/watchdog   # watchdog path, if set

#==============================================================#
# Monitor Settings
#==============================================================#
# default exporter settings
#exporter_metric_path: "/metrics"
#node_exporter_port: 9100
#pg_exporter_port: 9630
#pgbouncer_exporter_port: 9631

#==============================================================#
# Load Balancer Settings
#==============================================================#
#pg_lb_enabled:       true           # default load balancer type
#pg_lb_type:          haproxy        # haproxy | vip
#pg_lb_policy:        leastconn       # roundrobin, leastconn
#pg_lb_admin:         admin           # default admin user
#pg_lb_password:      admin           # default admin password
#pg_lb_admin_port:    9101            # default admin port 9101
#pg_lb_primary_port:  5433            # default primary port 5433
#pg_lb_replica_port:  5434            # default replica port 5434
#pg_lb_dest_port:     6432            # default target port is pgbouncer 6432
#pg_lb_check_port:    8008            # default health check port
#
#pg_lb_timeout_client: 3h
#pg_lb_timeout_server: 3h
#pg_lb_socket: /var/run/haproxy.socket


#################################################################
## vip
#################################################################
#
#keepalived_enabled: true      # enable keepalived for cluster
#keepalived_nic: eth1          # REQUIRED field nic interface

...
