---
################################################################
#               Variables override by meta node                #
################################################################

#==============================================================#
# Meta node
#==============================================================#
node_overwrite_hostname: false    # rather keep meta node's name

#==============================================================#
# Meta infra
#==============================================================#
# set to true to install build packages on meta node only
infra_build_essential_support: false

#==============================================================#
# Meta dcs
#==============================================================#
# meta node are used as dcs server
dcs_role: server         # meta dcs role: server

#==============================================================#
# Meta k8s
#==============================================================#
# meta node are used as k8s master
k8s_role: master         # meta k8s role: master


################################################################
#                    Meta ad-hoc variables                     #
################################################################

#==============================================================#
# Meta packages
#==============================================================#
# install for meta nodes only
meta_package_list:
  - ansible,python,python-pip,python-ipython,python-psycopg2                    # ansible and python environment
  - nginx,haproxy,keepalived,dnsmasq                                            # proxy and dns
  - grafana,prometheus2,pushgateway,alertmanager,node_exporter,nginx_exporter   # monitoring packages

#==============================================================#
# Meta grafana
#==============================================================#
meta_grafana_server: http://grafana.pigsty      # use pre-defined prometheus data source
meta_grafana_force_download_plugins: false      # force redownload grafana plugins
meta_grafana_time_interval: 2s                  # force redownload grafana plugins

meta_grafana_plugins:
  - simpod-json-datasource
  - camptocamp-prometheus-alertmanager-datasource
  - ryantxu-ajax-panel
  - grafana-piechart-panel
  - jdbranham-diagram-panel
  - aidanmountford-html-panel
  - alexandra-trackmap-panel
  - snuids-radar-panel
  - digrich-bubblechart-panel

meta_grafana_dashboards:
  - node
  - haproxy
  - pg-instance
  - pg-cluster
  - pg-query


#==============================================================#
# Meta dns server
#==============================================================#
# DNS record that resolved by DNS server on meta node
meta_dynamic_dns:
  - host: 10.10.10.10       # meta service domain name
    domain: [pigsty, consul.pigsty, grafana.pigsty, prometheus.pigsty, alertmanager.pigsty, admin.pigsty, yum.pigsty]
  - host: 10.10.10.10       # short alias
    domain: [c.pigsty, g.pigsty, p.pigsty, pg.pigsty, am.pigsty, ha.pigsty, k8s.pigsty, k.pigsty]
  - host: 10.10.10.2        # pg-meta default vip
    domain: [pg-meta, haproxy.pg-meta]
  - host: 10.10.10.3        # pg-test default vip
    domain: [pg-test, haproxy.pg-meta]



#==============================================================#
# MetaDB setup
#==============================================================#
# install options
pg_cluster: pg-meta
pg_version: 12                  # default postgresql version
pg_postgis_version: 30          # install postgis extension?
pg_postgis_install: true        # install postgis extension?
pg_extension_install: true      # install postgis extension?

pg_exists_action: skip          # if cluster already eixsts, what to do:
pg_default_username:   meta     # business passowrd (optional)
pg_default_password:   meta     # business passowrd (optional), may provide via secret files
pg_default_database:   meta     # business username (optional)

pg_lb_vip: 10.10.10.2
pg_lb_nic: eth1



################################################################
# Meta repo variable: how to build local yum repo
################################################################
# how to download
repo_force_download:   false     # force download even cache exists
repo_proxy_env: {}               # add proxy environment variable here

repo_package_list:
  # postgres core packages
  - postgresql13*
  - postgresql12*
  - postgis30_12*

  # postgres extension packages 12
  - wal2json12,pg_repack12,pg_qualstats12,pg_stat_kcache12,pgrouting_12,pg_cron_12,timescaledb_12,pglogical_12,pgpool-II-12
  # postgres common misc
  - pgbouncer,pgadmin4,pg_top,pgbadger,pgdg-redhat-repo
  # ansible and python environment
  - ansible,python,python-pip,python-ipython,python-psycopg2
  # system utils
  - ntp,chrony,uuid,readline,lz4,nc,pv,jq,vim,make,patch,bash,libxml2,libxslt,lsof,wget,unzip,git,numactl,grubby,zlib,openssl,perl-ExtUtils-Embed
  # network utils
  - bind-utils,net-tools,sysstat,tcpdump,socat,ipvsadm
  # monitoring packages
  - grafana,prometheus2,pushgateway,alertmanager,node_exporter,postgres_exporter,nginx_exporter,blackbox_exporter
  # dcs packages
  - consul,consul_exporter,consul-template,etcd
  # proxy and dns
  - nginx,haproxy,keepalived,dnsmasq

# download necessary url packages
repo_url_package_list:
  - name: pg_exporter-0.2.0-1.el7.x86_64.rpm
    url: https://github.com/Vonng/pg_exporter/releases/download/v0.2.0/pg_exporter-0.2.0-1.el7.x86_64.rpm
  - name: patroni-1.6.5-1.rhel7.x86_64.rpm
    url: https://github.com/cybertec-postgresql/patroni-packaging/releases/download/1.6.5-1/patroni-1.6.5-1.rhel7.x86_64.rpm
  - name: vip-manager_0.6-1_amd64.rpm
    url: https://github.com/cybertec-postgresql/vip-manager/releases/download/v0.6/vip-manager_0.6-1_amd64.rpm

#==============================================================#
# additional packages
#==============================================================#
# additional packages to be downloaded
repo_additional_package_list: []

# download cloud native packages: kubectl kubeadm helm docker, etc..
repo_cloud_native: true
repo_cloud_native_package_list:
  - docker-ce,docker-ce-cli,docker-ce-selinux,cri-tools,kubeadm,kubectl,kubelet,kubernetes-cni,rkt,helm

# download build essential packages: gcc, g++, rpmbuild, etc...
repo_build_essential: true
repo_build_essential_package_list:
  - gcc,gcc-c++,clang,coreutils,diffutils,rpm-build,rpm-devel,rpmlint,rpmdevtools
  - zlib-devel,openssl-libs,openssl-devel,pam-devel,libxml2-devel,libxslt-devel,openldap-devel,systemd-devel,tcl-devel,python-devel
...