---
#==============================================================#
# Stage 1: Create dbsu                                         #
#==============================================================#
# - import_tasks: dbsu.yml    # already initialized during infra provision

#==============================================================#
# Stage 2: Create Directory                                    #
#==============================================================#
- import_tasks: directory.yml

#==============================================================#
# Stage 3: Install Postgres                                    #
#==============================================================#
- import_tasks: install.yml

...