---
################################################################
# clean existing postgres
################################################################
# DANGEROUS! remove all postgres data of target machine
- name: Cleanup postgresql
  tags: pg_primary_clean
  block:
    - name: Stop patroni and postgres service
      ignore_errors: true
      systemd: name={{ item }} state=stopped enabled=no daemon_reload=yes
      with_items: [patroni, postgres]

    # in case that postgres is start manually via pg_ctl
    - name: Stop running postgres double check
      become_user: postgres
      shell: |
        pg_exist=$(ps aux | grep -v grep | grep -- '-D /pg/data' | grep pgsql | wc -l)
        if (( $pg_exist==1 )); then
            /usr/pgsql/bin/pg_ctl -D /pg/data stop
        fi
        exit 0

    - name: Remove existing /pg/data directory
      file: path=/pg/data state=absent
    - name: Recreate default /pg/data directory
      file: path=/pg/data state=directory owner=postgres group=postgres mode=0700
...