---
################################################################
# purge existing postgres
################################################################
# DANGEROUS! remove all postgres data of target machine
# BUT, this is your choice
- name: Cleanup postgresql
  tags: pg_clean
  become: yes
  become_user: root
  block:
    - name: Stop existing postgres service
      shell: |
        # first, gracefully stop service
        systemctl stop patroni
        systemctl stop postgres
        systemctl stop pgbouncer
        systemctl stop pg_exporter
        systemctl stop pgbouncer_exporter

        # then, manually stop service if still exists
        if ps aux | grep postgres | grep -v grep | grep -q -- '-D'; then
            pg_ctl -D {{ pg_data }} stop --mode=immediate
            ps aux | grep postgres | grep -v grep | grep -- '-D' | awk '{print $2}' | xargs -n1 -I{} kill -9 {}
        fi

        if ps aux | grep postgres | grep -v grep | grep -q -- '-D'; then
            ps aux | grep postgres | grep -v grep | grep -- '-D' | awk '{print $2}' | xargs -n1 -I{} kill -9 {}
            sleep 5 # if still alive, leave 5s grace peroid and force a kill -9
        fi

        if ps aux | grep postgres | grep -v grep | grep -q -- '-D'; then
            exit 1  # report failure if still alive
        fi
        exit 0

    - name: Remove existing postgres directories
      file: path={{ item }} state=absent
      with_items:
        - /pg
        - "{{ pg_fs_main }}/postgres"
        - "{{ pg_fs_bkup }}/postgres"

...