---
################################################################
# create default database
################################################################
- name: Create default database and user
  tags: pg_primary_createdb
  when: default_creation
  become_user: postgres
  block:
    #==============================================================#
    # default user
    #==============================================================#
    - name: Create default business dbuser
      postgresql_user:
        db: postgres
        name: "{{ default_username }}"
        password: "{{ default_password }}"
        role_attr_flags: LOGIN,INHERIT

    - name: Grant admin role to default user
      postgresql_membership: group=dbrole_admin target_roles={{ default_username }}

    #==============================================================#
    # default database
    #==============================================================#
    - name: Create default business database
      postgresql_db:
        db: "{{ default_database }}"
        owner: "{{ default_username }}"
        encoding: UTF-8
        lc_collate: C
        lc_ctype: C

    #==============================================================#
    # check default access
    #==============================================================#
    # add default user/pass to pgpass
    - name: Create pgpass with business userinfo
      lineinfile:
        path: /home/postgres/.pgpass
        line: "*:*:*:{{ default_username }}:{{ default_password }}"
        create: yes

    - name: Check business database connectivity
      become_user: postgres
      shell: psql -U {{ default_username }} -d {{ default_database }} -Atc 'SELECT 1;'
      when: default_creation

...