---
################################################################
# PHASE 1: [check] primary instance precondition
################################################################
- import_tasks: check.yml


################################################################
# PHASE 2: [clean] existing stuff
################################################################
- import_tasks: clean.yml


################################################################
# PHASE 3: initdb and config
################################################################
- import_tasks: initdb.yml


################################################################
# PHASE 4: launch & create sys users
################################################################
- import_tasks: bootstrap.yml


################################################################
# PHASE 5: default role system
################################################################
- import_tasks: role.yml


################################################################
# PHASE 6: templating database
################################################################
- import_tasks: template.yml


################################################################
# PHASE 7: createdb (bizdb bizuser creation)
################################################################
- import_tasks: createdb.yml


################################################################
# PHASE 8: register service and data source
################################################################
- import_tasks: register.yml


...