---
#==============================================================#
# Stage 1: Check Postgres Instance is not running              #
#==============================================================#
- import_tasks: check.yml


#==============================================================#
# Stage 2: Purge existing stuff
#==============================================================#
- import_tasks: clean.yml


#==============================================================#
# Stage 3: Create directory structure
#==============================================================#
- import_tasks: directory.yml
#

#==============================================================#
# Stage 4: Initdb on cluster primary
#==============================================================#
- import_tasks: initdb.yml
  when: pg_role == 'primary' and pg_initdb_method == 'initdb'

# TODO: implement
#- import_tasks: initdb-from-backup.yml
#  when: pg_is_primary and pg_initdb_method == 'backup'
#
#- import_tasks: initdb-from-upstream.yml
#  when: pg_is_primary and pg_initdb_method == 'upstream'
#
#- import_tasks: initdb-from-upstream.yml
#  when: pg_is_primary and pg_initdb_method == 'standby'


#==============================================================#
# Stage 5: Bootstrap, launch and create core users
#==============================================================#
- import_tasks: bootstrap.yml
  when: pg_role == 'primary'


#==============================================================#
# Stage 6: Default role
#==============================================================#
- import_tasks: role.yml
  when: pg_role == 'primary'


#==============================================================#
# Stage 7: Template database
#==============================================================#
- import_tasks: template.yml
  when: pg_role == 'primary'


#==============================================================#
# Stage 8: Create default database / users
#==============================================================#
- import_tasks: createdb.yml
  when: pg_role == 'primary'


#==============================================================#
# Stage 9: Override hostname
#==============================================================#
- name: Setup hostname to pg instance name
  tags: pg_hostname
  when: pg_overwrite_hostname
  hostname: name={{ pg_instance }}


#==============================================================#
# Stage 10: Data Source register
#==============================================================#
- import_tasks: register.yml


...