---
- name: Templating default database
  tags: pg_primary_template
  become_user: postgres
  block:
    #==============================================================#
    # copy and render template sql
    #==============================================================#
    - name: Render template scripts to remote
      copy: src={{ item }} dest=/tmp/{{ item }}
      with_items: "{{ pg_template_scripts }}"

    - name: Execute templating scripts on remote
      command: psql template1 -f /tmp/{{ item }}
      with_items: "{{ pg_template_scripts }}"
...