---
- name: Templating default database
  tags: pg_primary_template
  become_user: postgres
  block:
    #==============================================================#
    # copy and render template sql
    #==============================================================#
    - name: Render template scripts to remote
      template: src={{ item }} dest=/tmp/{{ item }}
      with_items: "{{ template_scripts }}"

    - name: Execute templating scripts on remote
      postgresql_query:
        db: template1
        path_to_script: /tmp/{{ item }}
      with_items: "{{ template_scripts }}"
...