---
#==============================================================#
# Stage 1: Meta nginx setup
#==============================================================#
- import_tasks: nginx.yml

#==============================================================#
# Stage 2: Meta dnsmasq server setup
#==============================================================#
- import_tasks: dnsmasq.yml

#==============================================================#
# Stage 3: Meta Prometheus setup
#==============================================================#
- import_tasks: prometheus.yml

#==============================================================#
# Stage 4: Meta grafana setup
#==============================================================#
- import_tasks: grafana.yml

...