---
#==============================================================#
# Stage 1: Meta packages install
#==============================================================#
- name: Install meta packages from yum
  tags: meta_install
  environment: "{{ meta_proxy_env }}"
  yum: name={{ meta_package_list }} disable_gpg_check=yes

#==============================================================#
# Stage 2: Meta nginx setup
#==============================================================#
- import_tasks: nginx.yml

#==============================================================#
# Stage 3: Meta dnsmasq service
#==============================================================#
- import_tasks: dns.yml


##==============================================================#
## Stage 4: Meta Prometheus setup
##==============================================================#
- import_tasks: prometheus.yml


##==============================================================#
## Stage 5: Meta grafana setup
##==============================================================#
- import_tasks: grafana.yml


##==============================================================#
## Stage 6: Meta service register
##==============================================================#
- name: Register meta service to consul
  tags: meta_register
  block:
    - name: Copy meta service definition
      template:
        src: "{{ item }}.json"
        dest: /etc/consul.d/{{ item }}.json
        owner: consul
        group: admin
        mode: 0660
      with_items:
        - svc-nginx
        - svc-nginx-exporter
        - svc-dnsmasq
        - svc-prometheus
        - svc-altermanager
        - svc-grafana

    - name: Reload consul to register service
      systemd: name=consul state=reloaded enabled=yes daemon_reload=yes
...