---
- name: Setup meta nginx
  tags: meta_nginx
  block:

    #==============================================================#
    # Install nginx (normally already installed during repo setup)
    #==============================================================#
    - name: Make sure nginx package installed
      package: name=nginx state=present


    #==============================================================#
    # Config nginx
    #==============================================================#
    - name: Copy additional nginx proxy conf
      template: src=nginx/{{ item }}.conf.j2 dest=/etc/nginx/conf.d/{{ item }}.conf
      with_items: [consul, grafana, prometheus, alertmanager]

    - name: Update default nginx index page
      template: src=nginx/index.html dest=/www/index.html


    #==============================================================#
    # Launch nginx
    #==============================================================#
    - name: Restart meta nginx service
      systemd: name=nginx state=restarted enabled=yes daemon_reload=yes

    - name: Wait for nginx service online
      wait_for: host=localhost port=80 state=started timeout=10


    #==============================================================#
    # Register nginx consul service
    #==============================================================#
    - name: Copy meta service definition
      template: src=consul-service/svc-nginx.json.j2 dest=/etc/consul.d/svc-nginx.json owner=consul group=admin mode=0660

    - name: Reload consul to register service
      systemd: name=consul state=reloaded enabled=yes daemon_reload=yes

    - name: Copy alertmanager service definition
      template: src=consul-service/svc-alertmanager.json.j2 dest=/etc/consul.d/svc-alertmanager.json owner=consul group=admin mode=0660

    - name: Reload consul to register dnsmasq
      systemd: name=consul state=reloaded enabled=yes daemon_reload=yes



#==============================================================#
# setup nginx exporter
#==============================================================#
- name: Setup meta nginx exporter
  tags: meta_nginx_exporter
  ignore_errors: true
  block:
    - name: Make sure nginx package installed
      package: name=nginx_exporter state=present

    - name: Config nginx_exporter options
      template: src=nginx_exporter.default.j2 dest=/etc/default/nginx_exporter

    - name: Restart nginx_exporter service
      systemd: name=nginx_exporter state=restarted enabled=yes daemon_reload=yes

    - name: Wait for nginx exporter online
      wait_for: host=localhost port=9113 state=started timeout=10


    #==============================================================#
    # Register nginx exporter consul service
    #==============================================================#
    - name: Copy meta service definition
      template: src=consul-service/svc-nginx-exporter.json.j2 dest=/etc/consul.d/svc-nginx-exporter.json owner=consul group=admin mode=0660

    - name: Reload consul to register service
      systemd: name=consul state=reloaded enabled=yes daemon_reload=yes

...