---
# download proxy
proxy_env: {}

# node packages
cloud_native:     false      # download kubectl kubeadm helm docker, etc..
build_essential:  false      # download gcc, g++, rpmbuild, etc...

node_package_list:
  - etcd,consul,haproxy,keepalived,node_exporter                                        # must have
  - uuid,readline,zlib,openssl,libxml2,libxslt,pgbouncer                                # pg util
  - lz4,nc,pv,jq,make,patch,bash,lsof,wget,unzip,git,numactl,grubby,perl-ExtUtils-Embed # basic utils
  - bind-utils,net-tools,sysstat,tcpdump,socat,ipvsadm,python-ipython,python-psycopg2   # net utils

# install for meta nodes
meta_package_list:
  - ansible,python,python-pip,python-ipython,python-psycopg2                    # ansible and python environment
  - nginx,haproxy,keepalived,dnsmasq                                            # proxy and dns
  - grafana,prometheus2,pushgateway,alertmanager,node_exporter,nginx_exporter   # monitoring packages


additional_package_list: []

grafana_url: "http://localhost:3000"
grafana_provision_datasources: true
grafana_provision_dashboards: true
grafana_provision_plugins: true
grafana_force_download_plugins: false
...