---
#==============================================================#
#                      Meta Provision                          #
#==============================================================#

#--------------------------------------------------------------#
# 0. DCS  (Setup via separated role dcs)                       #
#--------------------------------------------------------------#
dcs_type:    consul                           # default dcs server type: consul
dcs_check_interval: 15s                       # default service check interval (not used)
dcs_check_timeout:  3s                        # default service check timeout  (not used)

#--------------------------------------------------------------#
# 1. Nginx                                                     #
#--------------------------------------------------------------#
# prometheus, alertmanager, dnsmasq, consul domain name
repo_host:                yum.pigsty          # yum repo domain name
consul_domain_name:       c.pigsty            # consul ui domain name
grafana_domain_name:      g.pigsty            # grafana ui domain name
prometheus_domain_name:   p.pigsty            # prometheus ui domain name
alertmanager_domain_name:  am.pigsty           # alertmanager ui domain name

#--------------------------------------------------------------#
# 2. Dnsmasq
#--------------------------------------------------------------#
# DNS record that resolved by DNS server on meta node
dnsmasq_dns: []

#--------------------------------------------------------------#
# 3. Prometheus                                                #
#--------------------------------------------------------------#
prometheus_scrape_interval: 10s               # global scrape & evaluation interval
prometheus_scrape_timeout: 5s                 # scrape timeout
prometheus_metrics_path: /metrics             # default metrics path (only for job 'pg')
prometheus_data_dir: /export/prometheus/data  # prometheus data dir
prometheus_retention: 180d                    # how long to keep

#--------------------------------------------------------------#
# 4. Grafana                                                   #
#--------------------------------------------------------------#
grafana_force_download_plugins: false         # force redownload grafana plugins
grafana_time_interval: 2s                     # force redownload grafana plugins
grafana_provision_via_db: true                # provision via copy sqlite db by default
grafana_dashboards: []                        # default dashboards
grafana_plugins_install:                      # install grafana plugins ?
grafana_plugins_force_download:               # force re-download grafana plugins ?
grafana_plugins:                              # default grafana plugins list
  - camptocamp-prometheus-alertmanager-datasource
  - simpod-json-datasource
  - ryantxu-ajax-panel
  - jdbranham-diagram-panel

...