---
# docker & k8s
docker_cgroups_driver: systemd                                    # docker default cgroup fs driver
docker_registry_mirrors: []                                       # docker registry mirror
docker_image_cache: /www/pigsty/docker-images.tar.lz4             # docker images lz4 tar to be loaded
k8s_registry_mirrors: registry.aliyuncs.com/google_containers     # kubernetes versionaliyun k8s miiror repository

k8s_servers: []                                                   # kubernetes servers (REQUIRED)
k8s_version: 1.18.5                                               # kubernetes version
k8s_pod_cidr: "10.11.0.0/16"                                      # kubernetes pod network cidr
k8s_service_cidr: "10.12.0.0/16"                                  # kubernetes service network cidr
k8s_dashboard_admin_user: dashboard-admin-sa                      # kubernetes dashboard admin user name

k8s_role: node                                                    # default kubernetes role (override for masters)
...