---
#==============================================================#
# start postgresql primary service
#==============================================================#
- name: Launch PostgreSQL service
  tags: pg_primary
  when: pg_role == 'primary'
  block:
    #==============================================================#
    # start postgresql server @ 5432
    #==============================================================#
    # copy systemd service definition
    - name: Copy postgres systemd service file
      template:
        src: postgres.service.j2
        dest: /usr/lib/systemd/system/postgres.service

    - name: Launch postgres service on primary
      systemd: name=postgres state=restarted enabled=yes daemon_reload=yes

    - name: Waits for primary postgres online
      wait_for: host=localhost port=5432 state=started timeout=10

    - name: Check primary postgres service ready
      become_user: "{{ pg_dbsu }}"
      command: /usr/pgsql/bin/pg_isready
...