---
- name: Copy postgresql scripts
  tags: pg_scripts
  become: yes
  block:
    - name: Copy postgres scripts to /pg/bin/
      copy: src=pg/ dest=/pg/bin/ owner={{ pg_dbsu }} group=postgres mode=0755

    - name: Copy alias profile to /etc/profile.d
      copy: src=pg-alias.sh dest=/etc/profile.d/pg-alias.sh mode=0755

    - name: Copy psqlrc to postgres home
      copy: src=psqlrc dest="{{ pg_dbsu_home }}/.psqlrc" owner=postgres mode=0600

...