---
#--------------------------------------------------------------#
# 1. Setup Haproxy
#--------------------------------------------------------------#
- name: Setup Haproxy
  when: pg_lb_enabled and pg_lb_type == 'haproxy'
  tags: pg_haproxy
  block:
    - name: Fetch postgres cluster memberships
      set_fact:
        pg_memberships={{ hostvars| json_query(pg_membership_query) }}
      vars:
        pg_membership_query: "[@.*][0][?pg_cluster=='{{ pg_cluster }}'][@.pg_instance,@.inventory_hostname]"

    - name: Templating /etc/haproxyhaproxy.cfg
      template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

    - name: Copy haproxy systemd service file
      copy: src=haproxy.service dest=/usr/lib/systemd/system/haproxy.service

    - name: Launch haproxy load balancer service
      systemd:
        name: haproxy
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Wait for haproxy load balancer online
      wait_for: host=localhost port=9101 state=started timeout=10


#--------------------------------------------------------------#
# 2. Register Haproxy Service (optional)
#--------------------------------------------------------------#
- name: Register haproxy consul service
  tags: haproxy_register
  ignore_errors: true
  block:
    - name: Copy haproxy service definition
      template:
        src: svc-haproxy.json.j2
        dest: /etc/consul.d/svc-haproxy.json
        owner: consul
        group: postgres
        mode: 0660

    - name: Reload haproxy consul service
      systemd: name=consul state=reloaded



#--------------------------------------------------------------#
# 3. Setup keepalived
#--------------------------------------------------------------#
- name: Setup Keepalive
  when: pg_lb_enabled and pg_lb_vip_enabled
  tags: pg_vip
  block:

    # redhat/centos: chronyd already installed
    - name: Create keepalive config dir
      file: path=/etc/keepalived/conf.d state=directory mode=0755

    # redhat/centos: config chronyd
    - name: Copy top level keepalived.conf
      copy: dest=/etc/keepalived/keepalived.conf mode=0644
        content="include conf.d/*.conf"

    - name: Fetch cluster load balanacers for lb
      set_fact:
        pg_loadbalancers={{ hostvars| json_query(pg_loadbalancers_query) }}
      vars:
        pg_loadbalancers_query: "[@.*][0][?pg_cluster=='{{ pg_cluster }}' && pg_lb_enabled==true].inventory_hostname"

    - name: Copy keepalived.conf for cluster
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/conf.d/{{ pg_cluster }}.conf
        mode: 0644

    - name: Restart keepalived to take effect
      systemd: name=keepalived state=restarted enabled=yes



...