---
#==============================================================#
# Stage 1: Setup DNS and resolver
#==============================================================#
- import_tasks: docker.yml

#==============================================================#
# Stage 2: Setup kubernetes
#==============================================================#
- import_tasks: k8s.yml
...