#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   repo-init.yml
# Mtime     :   2020-06-20
# Desc      :   init repo node
# Path      :   repo-init.yml
# Author    :   Vonng(fengruohang@outlook.com)
# Note:
#
# Init a local yum repo powered by a local nginx web server
# all necessary rpm packages are downloaded to accelerate
# cluster initialization, or in case that target machine does
# not have internet access.
#
# RPM packages are downloaded to /www/{{ repo_name }}. And it will skip
# download if all packages are already downloaded in there.
#
# Local yum repo url:  http://{{ repo_host }}/{{ repo_name }}/
#==============================================================#
- name: Init local yum repo on node
  become: yes
  hosts: all
  gather_facts: no
  tags: repo

  vars:
    # dcs_type:    consul                  # default dcs server type: consul
    # dcs_servers: [10.10.10.10]           # default dcs servers
    # dcs_purge: true                      # force remove existing server
    # dcs_check_interval: 5s               # default service check interval
    # dcs_check_timeout:  1s               # default service check timeout

  roles:
    - role: dcs


...