#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   initdb.yml
# Mtime     :   2020-06-21
# Desc      :   init database based on provisioned cluster
# Path      :   initdb.yml
# Author    :   Vonng(fengruohang@outlook.com)
#==============================================================#

#==============================================================#
# This play will init a/several new database cluster according to inventory
#==============================================================#
- name: Init new database cluster
  become: yes
  hosts: all
  gather_facts: false

  roles:
    - role: proxy                        # init postgres
      tags: proxy

...
