#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   init-cluster.yml
# Mtime     :   2020-06-21
# Desc      :   init database cluster
# Path      :   init-cluster.yml
# Author    :   Vonng(fengruohang@outlook.com)
#==============================================================#


#==============================================================#
# This play will init a new database cluster according to inventory
#==============================================================#
- name: Init new database cluster
  become: yes
  hosts: all
  gather_facts: no
  roles:
    - role: node                            # node provision setup
      tags: node

    - role: dcs                             # dcs: consul/etcd
      tags: dcs

    # meta db setup (skip replica & haproxy)
    - role: pg_preflight                    # pre-flight & install
      tags: preflight

    - role: pg_install                      # install postgres packages
      tgas: install

    - role: pg_init                         # init postgres cluster
      tags: postgres

    - role: pg_patroni                      # init connection pooler
      tags: patroni

    - role: pg_pgbouncer                    # init connection pooler
      tags: pgbouncer

    - role: pg_monitor                      # init monitor system
      tags: monitor

    - role: haproxy                         # haproxy load balancer
      tags: haproxy

...
