#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   node-init.yml
# Mtime     :   2020-06-20
# Desc      :   init node
# Path      :   node-init.yml
# Author    :   Vonng(fengruohang@outlook.com)
#==============================================================#
- name: Init local yum repo on node
  become: yes
  hosts: all
  gather_facts: no
  tags: node
  vars:
  roles:
    - role: node          # tune node settings

...