#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   node.yml
# Mtime     :   2020-06-20
# Desc      :   init node
# Path      :   node-init.yml
# Author    :   Vonng(fengruohang@outlook.com)
#==============================================================#
- name: Provision Node
  become: yes
  hosts: all
  gather_facts: no
  tags: node

  roles:
    - role: node

...