#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   pg-meta.yml
# Mtime     :   2020-05-30
# Desc      :   init meta node
# Path      :   pg-meta.yml
# Author    :   Vonng(fengruohang@outlook.com)
# Note:
#
# Init a local yum repo powered by a local nginx web server
# all necessary rpm packages are downloaded to accelerate
# cluster initialization, or in case that target machine does
# not have internet access.
#
# RPM packages are downloaded to /www/pigsty. And it will skip
# download if all packages are already downloaded in there.
#==============================================================#
- name: Init meta node
  become: yes
  hosts: meta
  gather_facts: true
  tags: node-meta
  roles:
    - role: repo                # init local yum repo
    - role: node                # node provision setup
    - role: consul              # init consul servers
    - role: meta                # meta provision setup



- name: Init pg-meta database cluster on meta node(s)
  become: yes
  hosts: meta
  tags: pg-meta
  roles:
    # pre-flight & install
    - role: pg_preflight                  # check cluster topo and build primary & replica group
    - role: pg_install                    # install postgres packages, create users and dir

    # init primary
    - role: pg_primary                    # init primary instance
      when: role == 'primary'

    # init replica
    - role: pg_replica                    # init replica instance
      when: role != 'primary'

    # init pgbouncer
    - role: pg_pgbouncer                  # init connection pool

    # init ha agent (optional)
    - role: pg_patroni                    # init ha agent patroni
      when: ha_enabled

    # install load balancer (optional)
    - role: pg_proxy                      # haproxy and keepalived
      when: lb_enabled

    # deploy and register monitor service
    - role: pg_monitor                    # init monitoring system


...