#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   initdb.yml
# Mtime     :   2020-06-21
# Desc      :   init database based on provisioned cluster
# Path      :   initdb.yml
# Author    :   Vonng(fengruohang@outlook.com)
#==============================================================#


#==============================================================#
# This play will init a new database cluster according to inventory
#==============================================================#
- name: Init new database cluster
  become: yes
  hosts: all
  gather_facts: true
  roles:
    # meta db setup (skip replica & haproxy)
    - role: pg_preflight                    # pre-flight & install
      tags: preflight

    - role: pg_install                      # install postgres packages
      tgas: install

    - role: pg_init                         # init primary instance
      tags: postgres

    - role: pg_pgbouncer                    # init connection pooler
      tags: pgbouncer

    - role: pg_patroni                      # init connection pooler
      tags: patroni

    - role: pg_monitor                      # init monitor system
      tags: monitor

    - role: haproxy                         # haproxy load balancer
      tags: haproxy
...
