#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   postgres.yml
# Ctime     :   2020-04-13
# Mtime     :   2020-09-07
# Desc      :   init postgres cluster
# Path      :   postgres.yml
# Copyright (C) 2019-2020 Ruohang Feng
#==============================================================#

- name: Init database cluster
  become: yes
  hosts: all
  gather_facts: false

  roles:
    - role: postgres                        # init postgres
      tags: postgres

    - role: monitor                         # init monitor system
      tags: monitor

    - role: proxy                           # init proxy
      tags: proxy

...
