#!/usr/bin/env ansible-playbook
---
#==============================================================#
# Init a k8s cluster
#==============================================================#
- name: Init local yum repo
  become: yes
  hosts: meta
  gather_facts: true
  tags: repo
  roles:
    - repo                # init local yum repo

- name: Provision all nodes
  become: yes
  hosts: all
  gather_facts: true
  tags: node
  roles:
    - node                # provision all nodes
...