#!/usr/bin/env ansible-playbook
---
#==============================================================#
# Init a postgres cluster named pg-test on node-[1..3]
#==============================================================#
- name: Stop pg-test service
  become: yes
  hosts: all
  tags: test
  vars:
  tasks:
    - name: Stop all additional services on all nodes
      ignore_errors: true
      systemd: name={{ item }} state=stopped
      with_items:
        - patroni
        - pgbouncer
        - postgres
        - pg_exporter
        - pgbouncer_exporter
        - node_exporter
        - haproxy
        - consul

- name: Stop meta service
  become: yes
  hosts: all
  tags: test
  vars:
  tasks:
    - name: Stop all additional services on all nodes
      ignore_errors: true
      systemd: name={{ item }} state=stopped
      with_items:
        - prometheus
        - grafana
        - alertmanager
        - nginx_exporter
...