---
# - domain names - #
nginx_upstream:
  - {name: consul,        host: c.pigsty, url: "http://localhost:8500/"}
  - {name: grafana,       host: g.pigsty, url: "http://localhost:3000/"}
  - {name: prometheus,    host: p.pigsty, url: "http://localhost:9090/"}
  - {name: alertmanager,  host: a.pigsty, url: "http://localhost:9093/"}

# - reference : nginx local repo - #
repo_home: /www                               # default repo dir location
repo_address: yum.pigsty                      # local repo host (ip or hostname, including port if not using 80)
repo_port: 80                                 # repo server listen address, must same as repo_address!

# - reference : dcs metadata - #
dcs_type: consul                  # default dcs server type: consul
consul_check_interval: 15s        # default service check interval
consul_check_timeout:  1s         # default service check timeout
...
