---
pg_cluster_dir:   "{{ pg_fs_main }}/postgres/{{ pg_cluster }}-{{ pg_version }}"
pg_backup_dir:    "{{ pg_fs_bkup }}/postgres/{{ pg_cluster }}-{{ pg_version }}"

# this are variables build from pg_version and pg_role
# they will be override by  pg_conf_path and pg_hba_path if provided
pg_default_conf:  "postgresql-{{ pg_version }}.conf"
pg_default_hba:   "pg_hba-{{ pg_role }}.conf"
...