
---
lb_enabled: true
lb_role:    backup
lb_primary_port: 5555
lb_replica_port: 5556
# lb_interface: eth1      # You MUST explict designate default nic interface
# cluster_vip: x.x.x.x    # You MUST provide a vip explictly if lb is enabled
...