
---
# by default, all hosts that in play_hosts will perform as real ip group
# if keepalived_role = master is set for exact one host, that host will
# be used as MASTER by default. Otherwise, all hosts will have BACKUP role
# and preempt for MASTER.

lb_role: backup               # default load balancer role
keepalived_enabled: true      # enable keepalived for cluster
# keepalived_vip: 10.10.10.2    # REQUIRED field virtual vip address
# keepalived_nic: eth1          # REQUIRED field nic interface
# keepalived_rip: xxxx          # REQUIRED field rip list
...