---
################################################################
# purge existing postgres
################################################################
# DANGEROUS! remove all postgres data of target machine
# BUT, this is your choice
- name: Cleanup postgresql
  tags: pg_clean
  become: yes
  block:
    - name: Shutdown existing postgres service
      shell: |
        # first, gracefully stop service
        systemctl stop patroni
        systemctl stop postgres
        systemctl stop pgbouncer
        systemctl stop pg_exporter
        systemctl stop pgbouncer_exporter

        # then, manually stop service if still exists
        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
            pg_ctl -D {{ pg_data }} stop --mode=immediate
            ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D' | awk '{print $1}' | xargs kill -9
        fi

        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
            ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D' | awk '{print $1}' | xargs kill -9
            sleep 5 # if still alive, leave 5s grace peroid and force a kill -9
        fi

        if ps -u postgres -o pid:1,command | grep -E 'postmaster|postgres:|-D'  | grep checkpointer ; then
            exit 1  # report failure if still alive
        fi
        exit 0

    - name: Remove existing postgres directories
      file: path={{ item }} state=absent
      with_items:
        - /pg
        - "{{ pg_fs_main }}/postgres"
        - "{{ pg_fs_bkup }}/postgres"

...