---
#==============================================================#
# Create new database cluster with initdb
#==============================================================#
# initdb will create database cluster on pg_data dir

- name: Init primary database cluster
  tags: pg_initdb
  when: pg_role == 'primary'
  any_errors_fatal: true
  become: yes
  become_user: "{{ pg_dbsu }}"
  block:
    # create a new database cluster with initdb
    - name: Initialize primary database cluster
      command: "{{ pg_bin_dir }}/initdb -D {{ pg_data }} {{ pg_initdb_opts }}"

    # default config will be rename as postgresql.base.conf
    - name: Rename conf to postgresql.base.conf
      copy:
        remote_src: yes
        src: "{{ pg_data }}/postgresql.conf"
        dest: "{{ pg_data }}/postgresql.base.conf"

...
