---
#==============================================================#
# Stage 1: Check Postgres Instance is not running              #
#==============================================================#
- import_tasks: check.yml


#==============================================================#
# Stage 2: Purge existing stuff
#==============================================================#
- import_tasks: clean.yml


#==============================================================#
# Stage 3: Create directory structure
#==============================================================#
- import_tasks: directory.yml


#==============================================================#
# Stage 4: Initdb on cluster primary  (Primary only)
#==============================================================#
- import_tasks: initdb.yml
  when: pg_initdb_method == 'initdb'

# TODO: implement
#- import_tasks: initdb-from-backup.yml
#  when: pg_is_primary and pg_initdb_method == 'backup'
#
#- import_tasks: initdb-from-upstream.yml
#  when: pg_is_primary and pg_initdb_method == 'upstream'
#
#- import_tasks: initdb-from-upstream.yml
#  when: pg_is_primary and pg_initdb_method == 'standby'


#==============================================================#
# Stage 5: Config cluster primary  (Primary only)
#==============================================================#
- import_tasks: config.yml


#==============================================================#
# Stage 6: Launch primary instance
#==============================================================#
- import_tasks: primary.yml


#==============================================================#
# Stage 7: Bootstrap, launch and create core users (Primary only)
#==============================================================#
- import_tasks: bootstrap.yml


#==============================================================#
# Stage 8: Default role (Primary only)
#==============================================================#
- import_tasks: role.yml


#==============================================================#
# Stage 9: Template database (Primary only)
#==============================================================#
- import_tasks: template.yml


#==============================================================#
# Stage 10: Create default database / users  (Primary only)
#==============================================================#
- import_tasks: createdb.yml


#==============================================================#
# Stage 11: Create Pgpass
#==============================================================#
- import_tasks: pgpass.yml


#==============================================================#
# Stage 12: Create replica (Replica only)
#==============================================================#
- import_tasks: replica.yml


#==============================================================#
# Stage 13: Override hostname
#==============================================================#
- name: Setup hostname to pg instance name
  tags: pg_hostname
  when: pg_overwrite_hostname
  hostname: name={{ pg_instance }}


#==============================================================#
# Stage 14: Register service and data source
#==============================================================#
- import_tasks: register.yml

...