---
#==============================================================#
# Create pgpass file
#==============================================================#
- name: Write default userpass to .pgpass
  tags: pg_pass
  block:
    # add replication and monitor user to pgpass
    - name: Write pgpass with default userinfo
      copy:
        content: |
          *:*:*:{{ pg_replication_username }}:{{ pg_replication_password }}
          *:*:*:{{ pg_monitor_username }}:{{ pg_monitor_password }}
        dest: /home/postgres/.pgpass
        owner: postgres
        group: admin
        mode: 0600

    # add default user/pass to pgpass
    - name: Add default database user to pgpass
      when: pg_default_username != 'postgres'
      lineinfile:
        path: /home/postgres/.pgpass
        line: "*:*:*:{{ pg_default_username }}:{{ pg_default_password }}"

...