---
#==============================================================#
# Register postgres service
#==============================================================#
- name: Register postgres service to dcs
  tags: pg_register
  block:
    #==============================================================#
    # Register postgres to dcs
    #==============================================================#
    - name: Copy postgres service definition
      template:
        src: svc-postgres.json.j2
        dest: /etc/consul.d/svc-postgres.json
        owner: consul
        group: postgres
        mode: 0660

    - name: Copy consul node-meta definition
      template:
        src: node-meta.json.j2
        dest: /etc/consul.d/node-meta.json.j2
        owner: consul
        group: postgres
        mode: 0644

    - name: Restart consul to load new node-meta
      systemd: name=consul state=restarted


    #==============================================================#
    # Register postgres datasource if grafana_url is provided
    #==============================================================#
    # load it to data source
    - name: Create grafana datasource postgres
      when: grafana_url is defined
      ignore_errors: true
      grafana_datasource:
        name: "{{ pg_instance }}"
        grafana_url: "{{ grafana_url }}"
        grafana_user: "admin"
        grafana_password: "admin"
        ds_type: "postgres"
        ds_url: "{{ inventory_hostname }}:5432"
        database: "{{ pg_default_database }}"
        user: "{{ pg_monitor_username }}"
        password: "{{ pg_monitor_password }}"
        sslmode: "disable"
...