---
#==============================================================#
# create default role hierarchy: readonly / readwrite / admin
#==============================================================#
- name: Create default roles
  when: pg_role == 'primary'
  tags: pg_role
  become_user: postgres
  block:
    #==============================================================#
    # default roles: readonly / readwrite
    #==============================================================#
    - name: Create default role for read or write
      postgresql_user:
        db: postgres
        name: "{{ item }}"
        role_attr_flags: NOLOGIN,INHERIT
      with_items:
        - dbrole_readonly
        - dbrole_readwrite

    - name: Grant dbrole_readonly to readwrite
      postgresql_membership: group=dbrole_readonly target_roles=dbrole_readwrite,pg_monitor

    #==============================================================#
    # default roles: admin
    #==============================================================#
    - name: Create cluster default admin role
      postgresql_user:
        db: postgres
        name: dbrole_admin
        role_attr_flags: NOLOGIN,INHERIT,CREATEROLE,CREATEDB,BYPASSRLS
        groups:
          - pg_monitor
          - dbrole_readwrite

    - name: Grant dbrole_admin to dbsu postgres
      postgresql_membership: group=dbrole_admin target_roles=postgres


    #==============================================================#
    # change default privileges on postgres & template1
    #==============================================================#
    # object create by postgres and dbrole_admin will have their privileges properly set
    - name: Alter default privileges for roles
      postgresql_query:
        db: "{{ item }}"
        query: |
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT USAGE ON SCHEMAS TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT SELECT ON TABLES TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT SELECT ON SEQUENCES TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT EXECUTE ON FUNCTIONS TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT INSERT, UPDATE, DELETE ON TABLES TO dbrole_readwrite;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT USAGE, UPDATE ON SEQUENCES TO dbrole_readwrite;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLES TO dbrole_admin;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT CREATE ON SCHEMAS TO dbrole_admin;
          ALTER DEFAULT PRIVILEGES FOR ROLE dbrole_admin GRANT USAGE ON TYPES TO dbrole_admin;

          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SCHEMAS TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON SEQUENCES TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO dbrole_readonly;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT INSERT, UPDATE, DELETE ON TABLES TO dbrole_readwrite;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE, UPDATE ON SEQUENCES TO dbrole_readwrite;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT TRUNCATE, REFERENCES, TRIGGER ON TABLES TO dbrole_admin;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT CREATE ON SCHEMAS TO dbrole_admin;
          ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON TYPES TO dbrole_admin;
      with_items:
        - postgres
        - template1
...