---
# - reference - #
pg_namespace: /pg                             # top level key namespace in dcs
exporter_metrics_path: "/metrics"

# - vip - #
vip_enabled: false                            # level2 vip requires primary/standby under same switch
vip_address: 127.0.0.1                        # virtual ip address ip/cidr
vip_cidrmask: 24                              # virtual ip address cidr mask
vip_interface: eth0                           # virtual ip network interface

# - haproxy - #
haproxy_enabled: true                         # enable haproxy among every cluster members
haproxy_policy: leastconn                     # roundrobin, leastconn
haproxy_admin_username: admin                 # default haproxy admin username
haproxy_admin_password: admin                 # default haproxy admin password
haproxy_client_timeout: 3h                    # client side connection timeout
haproxy_server_timeout: 3h                    # server side connection timeout
haproxy_exporter_port: 9101                   # default admin/exporter port
haproxy_check_port: 8008                      # default health check port (patroni 8008 by default)
haproxy_primary_port:  5433                   # default primary port 5433
haproxy_replica_port:  5434                   # default replica port 5434
haproxy_backend_port:  6432                   # default target port: pgbouncer:6432 postgres:5432
...