---
################################################################
# node provision
################################################################

#==============================================================#
# node basics
#==============================================================#
# node hostname override : use {{ cluseter }}-{{ seq } if defined
node_overwrite_hostname: true

# node timezone override
node_timezone: 'Asia/Shanghai'     # default node timezone

#==============================================================#
# node features
#==============================================================#
# node feature switch
node_disable_numa: false        # [VERY IMPORTANT] disable numa, skip for vm or single CPU setup
node_disable_swap: true         # [VERY IMPORTANT] disable swap for pg and kubernetes
node_disable_thp: true          # [VERY IMPORTANT] disable transparent huge page
node_disable_firewall: true     # disable firewall to allow haproxy and kubernetes
node_disable_selinux: true      # disable selinux
node_cpupower_performance: true # set cpupower governor to performance mode if available
node_disk_prefetch: false       # setup disk prefetch on HDD to increase performance

# node kernel modeles
node_kernel_modules: [softdog, br_netfilter, ip_vs, ip_vs_rr, ip_vs_rr, ip_vs_wrr, ip_vs_sh, nf_conntrack_ipv4]


#==============================================================#
# node sysctl
#==============================================================#
node_sysctl_dynamic_tune: true  # set some param based on node fact
# additional sysctl parameters (overwrite with your own)
node_sysctl_params:


#==============================================================#
# node static dns
#==============================================================#
node_static_dns:
  - host: 127.0.0.1
    domain: [localhost]
...
