---
################################################################
# node provision
################################################################

#==============================================================#
# node basics
#==============================================================#
# node hostname override : use {{ pg_cluseter }}-{{ pg_seq } if available
node_overwrite_hostname: false

# node timezone override
node_timezone: 'Asia/Shanghai'     # default node timezone

#==============================================================#
# node features
#==============================================================#
# node feature switch
node_disable_numa: false        # [VERY IMPORTANT] disable numa, skip for vm or single CPU setup
node_disable_swap: true         # [VERY IMPORTANT] disable swap for pg and kubernetes
node_disable_firewall: true     # disable firewall to allow haproxy and kubernetes
node_disable_selinux: true      # disable selinux
node_disk_prefetch: false       # setup disk prefetch on HDD to increase performance

# node kernel modeles
node_kernel_modules: [softdog, br_netfilter, ip_vs, ip_vs_rr, ip_vs_rr, ip_vs_wrr, ip_vs_sh, nf_conntrack_ipv4]


#==============================================================#
# node sysctl
#==============================================================#
node_tune: true                 # tune node parameters
node_sysctl_params: {}          # additional sysctl parameters

#==============================================================#
# node users
#==============================================================#
node_root_setup: false          # setup root user(ssh exchange) ?

#==============================================================#
# node static dns
#==============================================================#
node_static_dns:                # write localhost to static dns
  - host: 127.0.0.1
    domain: [localhost]

...
