---
################################################################
# infra provision
################################################################


#==============================================================#
# infra provision
#==============================================================#
infra_local_repos: []                 # local yum repo file path
infra_disable_external_repo: false    # disable all other repos except local
infra_proxy_env: {}                   # add proxy environment variable here

# common infra packages
infra_packages:
  - etcd,consul,haproxy,keepalived,node_exporter,chrony,ntp                             # must have
  - uuid,readline,zlib,openssl,libxml2,libxslt,pgbouncer                                # pg util
  - lz4,nc,pv,jq,make,patch,bash,lsof,wget,unzip,git,numactl,grubby,perl-ExtUtils-Embed # basic utils
  - bind-utils,net-tools,sysstat,tcpdump,socat,ipvsadm,python-ipython,python-psycopg2   # net utils

# cloud native support
infra_cloud_native_support: false
infra_cloud_native_packages:
  - docker-ce,docker-ce-cli,rkt,kubelet,kubectl,kubeadm,kubernetes-cni,helm

# build toolchain support
infra_build_essential_support: false
infra_build_essential_packages:
  - gcc,gcc-c++,clang,coreutils,diffutils,rpm-build,rpm-devel,rpmlint,rpmdevtools
  - zlib-devel,openssl-libs,openssl-devel,pam-devel,libxml2-devel,libxslt-devel,openldap-devel,systemd-devel,tcl-devel,python-devel

# add additional packages here
infra_additional_packages: []   # additional rpm packages to be downloaded/installed

# infrastructure metadata
infra_dns_servers: []           # default DNS server
infra_ntp_servers: []           # default NTP server
...