---
#==============================================================#
# Cleanup existing pgbouncer
#==============================================================#
- name: Cleanup pgbouncer
  tags: pgbouncer_cleanup
  block:
    - name: Stop existing pgbouncer service
      ignore_errors: true
      systemd: name=pgbouncer state=stopped enabled=no daemon_reload=yes

    - name: Remove existing pgbouncer dirs
      file: path={{ item }} state=absent
      with_items:
        - /etc/pgbouncer
        - /var/log/pgbouncer
        - /var/run/pgbouncer

    - name: Recreate dirs with owner postgres
      file: path={{ item }} state=directory owner={{ pg_dbsu }} group=postgres mode=0750
      with_items:
        - /etc/pgbouncer
        - /var/log/pgbouncer
        - /var/run/pgbouncer
...