---
#==============================================================#
# Check pgbouncer installed
#==============================================================#
- name: Check pgbouncer is installed
  tags: pgbouncer_check
  shell: "[[ -f /bin/pgbouncer ]]"


#==============================================================#
# Cleanup existing pgbouncer
#==============================================================#
- import_tasks: cleanup.yml


#==============================================================#
# Config pgbouncer
#==============================================================#
- import_tasks: config.yml


#==============================================================#
# Launch pgbouncer
#==============================================================#
- import_tasks: launch.yml


#==============================================================#
# Register pgbouncer service (optional)
#==============================================================#
- name: Register pgbouncer service to consul
  tags: pgbouncer_register
  ignore_errors: true
  block:
    - name: Copy pgbouncer service definition
      template:
        src: svc-pgbouncer.json.j2
        dest: /etc/consul.d/svc-pgbouncer.json
        owner: consul
        group: admin
        mode: 0660

    - name: Reload consul to load new node-meta
      systemd: name=consul state=reloaded

...