---

# - postgres monitor settings - #
exporter_metric_path: "/metrics"
node_exporter_port: 9100
pg_exporter_port: 9630
pgbouncer_exporter_port: 9631


# - dcs variables reference - #
dcs_type: consul
consul_check_interval: 15s        # default service check interval
consul_check_timeout:  1s         # default service check timeout


# - postgres variables reference - #
pg_default_database: 'postgres'
pg_monitor_username: 'dbuser_monitor'
pg_monitor_password: 'dbuser_monitor'
...