---
#==============================================================#
# Postgres Install Options
#==============================================================#
#==============================================================#
# Postgres Install Options
#==============================================================#
pg_version: 12                  # default postgresql version
pg_dbsu:  postgres              # postgresql dbsu (currently setup during node provision)
pg_home:  /usr/pgsql            # postgresql binary installed path


#==============================================================#
# Postgres Initdb Options
#==============================================================#
# important host variables
# pg_cluster:                   # [REQUIRED] cluster name (already validate during pg_preflight)
# pg_seq: 0                     # [REQUIRED] instance seq (already validate during pg_preflight)
pg_role: replica                # [REQUIRED] service role (already validate during pg_preflight)

pg_exists: false
pg_exists_action: skip          # if cluster already eixsts, what to do:
                                #     - abort: abort entire play's execution (default)
                                #     - clean: remove existing cluster
                                #     - skip: only

pg_data: /pg/data               # postgres data directory
pg_port: 5432                   # postgres port

# directory structure
pg_fs_main: /export             # main disk monutpoint (or /data is another common mountpoint)
pg_fs_bkup: /var/backups        # backup mountpoint
pg_overwrite_hostname: true     # overwrite node hostname with pg instance name

# pg_conf_path:                 # user-providede postgresql.conf
# pg_hba_path:                  # user-providede pg_hba.conf

# system user: replication and monitor (important!)
pg_replication_username: 'replicator'   # replication user
pg_replication_password: 'replicator'
pg_monitor_username: 'dbuser_monitor'   # monitor user
pg_monitor_password: 'dbuser_monitor'
# default database and users
pg_default_database: 'postgres'
pg_default_username: 'postgres'
pg_default_password: 'postgres'

...