---

#==============================================================#
# Stage 4: Download yum packages
#==============================================================#
- name: Download local repo packages
  block:
    # install official and 3rd party yum repo
    - name: Install default centos yum repos
      environment: "{{ repo_proxy_env }}"
      yum: name=epel-release,centos-release-scl,centos-release-scl-rh

    - name: Enable default centos yum repos
      ignore_errors: true
      command: yum-config-manager --enable epel-release

    - name: Install additional yum repos
      copy: src=repo/{{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo mode=0644
      with_items: [centos-sclo-rh, centos-sclo-sclo, haproxy, postgres, grafana, prometheus, docker, harbottle, k8s]

    # enlist build essential packages if flag `build_essential` is set
    - name: Enlist building packages to repo
      when: repo_build_essential
      set_fact: repo_package_list="{{ repo_package_list + repo_build_essential_package_list }}"

    # enlist additional packages if provided
    - name: Enlist addional packages to repo
      when: repo_additional_package_list|length > 0
      set_fact: repo_package_list="{{ repo_package_list + repo_additional_package_list }}"

    - name: Print packages to be downloaded
      debug: {"msg": "Packages to be downloaded: {{ repo_package_list }}"}

    # download rpms, may take 1hour or more
    - name: Download packages to /www/pigsty
      environment: "{{ repo_proxy_env }}"
      yum:
        download_only: yes
        download_dir: /www/pigsty
        disable_gpg_check: yes
        name: "{{ repo_package_list }}"

    # download rpm from url
    - name: Download additional url packages
      environment: "{{ repo_proxy_env }}"
      get_url: dest=/www/pigsty/{{ item.name }} url={{ item.url }}
      with_items: "{{ repo_url_package_list }}"

    # dowload cloud native packages alone
    - name: Download cloud native packages
      when: repo_cloud_native
      yum:
        download_only: yes
        download_dir: /www/pigsty
        disable_gpg_check: yes
        name: "{{ repo_cloud_native_package_list }}"

    # create repo
    - name: Create local yum repo index
      command: createrepo /www/pigsty

    # set complete flag
    - name: Mark local yum repo complete
      copy: content=ok dest=/www/pigsty/repo_complete
...