---
#==============================================================#
# Stage 1: Precheck                                            #
#==============================================================#
- name: Local repo boostrap precheck
  tags: repo_precheck
  block:
    # Pre Condition: make sure cache dir /www/pigsty/boot exists
    - name: Create local repo directory
      file: path=/www/pigsty/boot state=directory mode=0755

    # Condition Check: whether normal rpm cache already exists
    # flag file: /www/pigsty/repo_complete exist indicate a valid cache
    - name: Check pigsty repo cache exists
      stat: path=/www/pigsty/repo_complete
      register: repo_cache

    # Condition Check: whether bootstrap cache already exists
    - name: Check pigsty boot cache exists
      stat: path=/www/pigsty/boot/boot_complete
      register: repo_boot_cache


#==============================================================#
# Stage 2: Download bootstrap pacakges if boot cache not exist #
#==============================================================#
- import_tasks: bootstrap.yml
  tags: repo_bootstrap
  when: not repo_boot_cache.stat.exists

#==============================================================#
# Stage 3: Boostrap yum repo nginx server                      #
#==============================================================#
- import_tasks: nginx.yml
  tags: repo_nginx

#==============================================================#
# Stage 3: Boostrap yum repo nginx server                      #
#==============================================================#
- import_tasks: download.yml
  tags: repo_download
  when: not repo_cache.stat.exists or repo_force_download

#==============================================================#
# Stage 5: Install local yum repo on current node
#==============================================================#
- name: Install local yum repos on meta
  tags: repo_install
  copy: src=repo/pigsty.repo dest=/etc/yum.repos.d/pigsty.repo mode=0666
...