---
#==============================================================#
# Stage 3: bootstrap local yum repo nginx server
#==============================================================#
- name: Bootstrap local yum repo
  block:
    - name: Install bootstrap packages (nginx)
      shell: cd /www/pigsty/boot && yum localinstall -q -y *.rpm

    - name: Copy default nginx server config
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf

    - name: Copy default nginx index page
      copy: src=index.html dest=/www/index.html

    - name: Copy nginx pigsty repo files
      copy: src=repo/pigsty.repo dest=/www/pigsty.repo

    - name: Start nginx service to serve repo
      systemd: name=nginx state=restarted enabled=yes daemon_reload=yes

    - name: Waits yum repo nginx online
      wait_for: host=localhost port=80 state=started

...