---
- name: Node disable firewall
  tags: node_firewall
  ignore_errors: true
  block:
    # - disable firewall - #
    - name: Node configure disable firewall
      when: node_disable_firewall
      systemd: name=firewalld state=stopped enabled=no

    # - disable selinux - #
    - name: Node disable selinux by default
      when: node_disable_selinux
      selinux: state=disabled
...
