---
- name: Install additional kernel modules
  tags: node_kernel
  block:
    - name: Enable linux kernel modules
      modprobe: name={{ item }} state=present
      with_items: "{{ node_kernel_modules }}"

    - name: Enable kernel module on reboot
      template: src=kernel.modules.j2 dest=/etc/sysconfig/modules/kernel.modules mode=0755
...
