---
#==============================================================#
# Stage 1: Hostname setup
#==============================================================#
- name: Setup node default hostname
  tags: node_hostname
  when: node_overwrite_hostname and cluster is defined and seq is defined
  hostname: name={{ cluster }}-{{ seq }}

#==============================================================#
# Stage 2: Timezone setup
#==============================================================#
- name: Setup node default timezone
  tags: node_timezone
  when: node_timezone is defined and node_timezone != ""
  timezone: name={{ node_timezone }}

#==============================================================#
# Stage 3: Profile setup
#==============================================================#
- name: Copy default user bash profile
  tags: node_profile
  copy: src=profile.sh dest=/etc/profile.d/profile.sh mode=755

#==============================================================#
# Stage 4: node feature setup
#==============================================================#
- import_tasks: feature.yml
  tags: node_feature

#==============================================================#
# Stage 5: node kernel module
#==============================================================#
- import_tasks: kernel.yml
  tags: node_kernel

#==============================================================#
# Stage 6: node sysctl
#==============================================================#
- import_tasks: sysctl.yml
  tags: node_sysctl
- import_tasks: sysctl_dynamic.yml
  tags: node_sysctl_dynamic_tune


#==============================================================#
# Stage 7: node ulimit
#==============================================================#
- name: Setup node default pam ulimits
  tags: node_ulimit
  copy: src=limits.conf dest=/etc/security/limits.d/limits.conf mode=0644

...
