---
#==============================================================#
# Stage 1: Hostname setup
#==============================================================#
- name: Setup node default hostname
  tags: node_hostname
  when: node_overwrite_hostname and pg_cluster is defined and pg_seq is defined
  hostname: name={{ pg_cluster }}-{{ pg_seq }}


#==============================================================#
# Stage 2: Timezone setup
#==============================================================#
- name: Setup node default timezone
  tags: node_timezone
  when: node_timezone is defined and node_timezone != ""
  timezone: name={{ node_timezone }}


#==============================================================#
# Stage 3: node feature setup
#==============================================================#
- import_tasks: feature.yml
  tags: node_feature


#==============================================================#
# Stage 4: node kernel module
#==============================================================#
- import_tasks: kernel.yml
  tags: node_kernel


#==============================================================#
# Stage 5: node sysctl
#==============================================================#
- import_tasks: tuned.yml

#==============================================================#
# Stage 6: node users
#==============================================================#
- import_tasks: users.yml


#==============================================================#
# Stage 6: node static dns
#==============================================================#
- name: Add static dns records to node
  tags: node_dns
  block:
#    - name: Write static dns record to node
#      lineinfile: path=/etc/hosts line="{{ inventory_hostname }} {{ ansible_nodename }}"

    - name: Write static dns record to node
      lineinfile: path=/etc/hosts line="{{ item.host }} {{ item.domain | join(' ') }}"
      with_items: "{{ node_static_dns }}"

...
