---
#==============================================================#
# Stage 1: node features
#==============================================================#
- import_tasks: feature.yml
  tags: node_feature

#==============================================================#
# Stage 2: node kernel module
#==============================================================#
- import_tasks: kernel.yml
  tags: node_kernel

#==============================================================#
# Stage 3: node tuned
#==============================================================#
- import_tasks: tuned.yml

#==============================================================#
# Stage 4: node users
#==============================================================#
- import_tasks: users.yml

#==============================================================#
# Stage 5: node dns
#==============================================================#
- import_tasks: dns.yml

#==============================================================#
# Stage 6: node repo
#==============================================================#
- import_tasks: repo.yml

#==============================================================#
# Stage 7: node pkgs
#==============================================================#
- import_tasks: pkgs.yml

#==============================================================#
# Stage 8: node ntp
#==============================================================#
- import_tasks: ntp.yml

#==============================================================#
# Stage 9: node vip
#==============================================================#
- import_tasks: vip.yml

...
