---
#==============================================================#
# Stage 1: Setup DNS and resolver
#==============================================================#
- name: Setup node DNS and resolver
  tags: node_dns
  block:
    - name: Overwrite /etc/hosts config
      template: src=hosts dest=/etc/hosts

    - name: Add resovler to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ default_dns_server }}"


#==============================================================#
# Stage 2: Disable SE Linux
#==============================================================#
- name: Setup node DNS and resolver
  tags: node_selinux
  block:
    - name: Set SELinux to permissive mode
      selinux: policy=targeted state=permissive
    - name: Disable selinux by setenforce 0
      command: setenforce 0


#==============================================================#
# Stage 3: Tune node settings
#==============================================================#
- name: Tune node settings
  tags: node_tune
  block:
    # disable swap is important for database and k8s
    - name: Node configure disable swap
      when: node_disable_swap
      command: swapoff -a
    - name: Node configure unmount swap
      mount: name={{ item }} fstype=swap state=absent
      with_items: [swap, none]

    # disable transparent huge page (important for DB)
    - name: Disable transparent hugepage
      when: node_disable_thp
      script: disable_thp.sh

    - name: Node configure disable firewall
      when: node_disable_firewall
      systemd: name=firewalld state=stopped enabled=on

    - name: Node configure disk prefetch
      when: node_disk_prefetch
      script: disk_prefetch.sh

    - name: Node configure enable watchdog
      when: node_enable_watchdog
      script: enable_watchdog.sh

    - name: Node configure disable numa
      when: node_disable_numa
      script: disable_numa.sh


#==============================================================#
# Stage 4: Install kernel modules
#==============================================================#
- name: Install additional kernel modules
  tags: node_kernel
  block:
    - name: Install additional kernel modules
      modprobe:
        name: 8021q
        state: present
      with_items: "{{ node_kernel_modules }}"

    - name: Load kernel module on node start
      copy: src=ipvs.modules dest=/etc/sysconfig/modules/ipvs.modules mode=0755


#==============================================================#
# Stage 5: Change sysctl parameters
#==============================================================#
- name: Change sysctl.conf parameters
  tags: node_sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: "{{ sysctl_params }}"


#==============================================================#
# Stage 6: Create default user/group
#==============================================================#
- name: Create node users
  tags: node_user
  block:
    - name: Create os user group postgres
      group: name=postgres gid=256
    - name: Create os user postgres:postgres
      user: name=postgres group=postgres home=/home/postgres generate_ssh_key=yes
    - name: Create os user prometheus:postgres
      user: name=prometheus group=postgres create_home=no
    - name: Create os user consul:postgres
      user: name=consul group=postgres create_home=no
    - name: Create os user etcd:postgres
      user: name=etcd group=postgres create_home=no

- name: Install node profile
  tags: node_profile
  block:
    - name: Copy default user bash profile
      copy: src=profile.sh dest=/etc/profile.d/profile.sh mode=644


#==============================================================#
# Stage 7: Install Local yum repo
#==============================================================#
- name: Install local yum repo
  tags: node_repo
  block:
    - name: Install local yum repo for node
      copy: src=pigsty.repo dest=/etc/yum.repos.d/pigsty.repo mode=0666

    - name: Configure node using local repo
      ignore_errors: true
      shell: |
        yum-config-manager --disable '*';
        yum-config-manager --enable pigsty ;
        yum clean all;
        exit 0

    - name: Install cloud repo if enabled
      when: cloud_native
      copy: src=cloud_native.repo dest=/etc/yum.repos.d/cloud.repo mode=0666



#==============================================================#
# Stage 8: Install node packages
#==============================================================#
- name: Install node packages
  tags: node_install
  block:
    # enlist cloud native packages if flag `cloud_native` is set
    - name: Install cloud native packages
      when: cloud_native is defined and cloud_native|bool
      set_fact: node_package_list="{{ node_package_list + cloud_native_package_list }}"

    # enlist build essential packages if flag `build_essential` is set
    - name: Install build essential packages
      when: build_essential is defined and build_essential|bool
      set_fact: node_package_list="{{ node_package_list + build_essential_package_list }}"

    # enlist additional packages if provided
    - name: Install additional node packages
      when: additional_package_list|length > 0
      set_fact: node_package_list="{{ node_package_list + additional_package_list }}"

    - name: Install node packages from yum
      environment: "{{ proxy_env }}"
      yum:
        disable_gpg_check: yes
        name: "{{ node_package_list }}"



#==============================================================#
# Stage 9: Setup ntp service
#==============================================================#
- name: Set ntp service chronyd
  tags: node_ntp
  when: ansible_os_family == "RedHat"
  block:
    # redhat/centos: chronyd already installed
    - name: Install chronyd package on node
      environment: "{{ proxy_env }}"
      package: name=chrony state=present

    # redhat/centos: config chronyd
    - name: Copy the chrony.conf template
      template: src=chrony.conf dest=/etc/chrony.conf

    - name: Launch chronyd ntpd service
      systemd: name=chronyd enabled=true state=restarted

    - name: Set local timezone and synctime
      timezone: name={{ default_timezone }}


...
