---
#==============================================================#
# Stage 1: node dns
#==============================================================#
- import_tasks: dns.yml

#==============================================================#
# Stage 2: node pkgs
#==============================================================#
- import_tasks: pkgs.yml

#==============================================================#
# Stage 3: node features
#==============================================================#
- import_tasks: feature.yml

#==============================================================#
# Stage 4: node kernel module
#==============================================================#
- import_tasks: kernel.yml

#==============================================================#
# Stage 5: node tuned
#==============================================================#
- import_tasks: tuned.yml

#==============================================================#
# Stage 6: node users
#==============================================================#
- import_tasks: users.yml

#==============================================================#
# Stage 7: node ntp
#==============================================================#
- import_tasks: ntp.yml

#==============================================================#
# Stage 8: node vip
#==============================================================#
#- import_tasks: vip.yml

...
