---
#--------------------------------------------------------------#
# 1. DNS
#--------------------------------------------------------------#
- import_tasks: dns.yml

#--------------------------------------------------------------#
# 2. Firewall
#--------------------------------------------------------------#
- import_tasks: firewall.yml

#--------------------------------------------------------------#
# 3. Packages
#--------------------------------------------------------------#
- import_tasks: pkgs.yml

#--------------------------------------------------------------#
# 4. Features
#--------------------------------------------------------------#
- import_tasks: feature.yml

#--------------------------------------------------------------#
# 5. Kernel Module
#--------------------------------------------------------------#
- import_tasks: kernel.yml

#--------------------------------------------------------------#
# 6. Tune
#--------------------------------------------------------------#
- import_tasks: tuned.yml

#--------------------------------------------------------------#
# 7. Users
#--------------------------------------------------------------#
- import_tasks: users.yml

#--------------------------------------------------------------#
# 8. NTP
#--------------------------------------------------------------#
- import_tasks: ntp.yml

...
