---
- name: Install node packages
  tags: node_pkgs
  block:

    # install common node packages
    - name: Install node basic packages
      environment: "{{ node_proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_packages }}"

    - name: Install node extra packages
      environment: "{{ node_proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_extra_packages }}"

    - name: Install node meta packages
      when: meta_node|bool
      environment: "{{ node_proxy_env | default({}) }}"
      yum: name={{ item }} disable_gpg_check=true
      with_items: "{{ node_meta_packages }}"

...
