---
- name: Install pigsty yum repo
  tags: node_repo
  block:
    # remove existing repos to backup dir
    - name: Backup existing repos
      when: node_repo_remove
      shell:
        warn: no
        cmd: mkdir -p /etc/yum.repos.d/backup ; mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/; true

    # install repo via url (usually a local yum repo)
    - name: Install local yum repo
      get_url:
        url: "{{ item }}"
        dest: /etc/yum.repos.d/{{ item | basename }}
      with_items: "{{ node_repo_url }}"

    # install upstream repo (in absence of local yum repo)
    - name: Install upstream repo
      when: repo_upstreams is defined
      yum_repository: "{{ item }}"
      with_items: "{{ repo_upstreams }}"

    # if node_repo_config given, use it and use it only
    - name: Config using local repo
      when: node_local_repo != ""
      ignore_errors: true           # in case that yum-util is not installed
      command: yum-config-manager --{{ item }}
      with_items:
        - "disable *"
        - "enable {{ node_local_repo }}"

    # otherwise, execute yum config command
    - name: Run yum config manager command
      when: node_local_repo == ""
      ignore_errors: true           # in case that yum-util is not installed
      command: yum-config-manager --{{ item }}
      with_items: "{{ node_repo_config }}"

...
