---
#==============================================================#
# Stage 1: DNS & Resovler
#==============================================================#
- name: Add resovler to /etc/resolv.conf
  tags: infra_dns
  when: infra_setup_dns
  lineinfile: path=/etc/resolv.conf line="nameserver {{ item }}"
  with_items: infra_dns_servers

#==============================================================#
# Stage 2: NTP service
#==============================================================#
- name: Set ntp service chronyd
  tags: infra_ntp
  when: infra_setup_ntp
  block:
    - name: Copy the chrony.conf template
      template: src=chrony.conf dest=/etc/chrony.conf
    - name: Launch chronyd ntpd service
      systemd: name=chronyd enabled=true state=restarted

#==============================================================#
# Stage 4: Setup VIP (basic keepalived structure)
#==============================================================#
- import_tasks: vip.yml
...
