---
#==============================================================#
# Stage 1: Install local yum repo
#==============================================================#
- name: Install local yum repo
  tags: infra_repo
  block:
    - name: Enlisting cloud native repo
      when: infra_cloud_native_support
      set_fact: infra_local_repos="{{ infra_local_repos + ['cloud_native.repo'] }}"

    - name: Install local yum repo for node
      copy: src={{ item }} dest=/etc/yum.repos.d/{{ item }} mode=0666
      with_items: "{{ infra_local_repos }}"

    - name: Disable all default yum repo
      when: infra_disable_external_repo
      ignore_errors: true
      command: yum-config-manager --disable '*';

    - name: Enable local repo to accelerate
      when: infra_disable_external_repo
      ignore_errors: true
      command: yum-config-manager --enable {{ item }}
      with_items: infra_local_repos


#==============================================================#
# Stage 2: Install packages
#==============================================================#
- name: Install infrastructure packages
  tags: infra_install
  block:
    # enlist cloud native packages if flag `cloud_native` is set
    - name: Enlist cloud native packages
      when: infra_cloud_native_support
      set_fact: infra_packages="{{ infra_packages + infra_cloud_native_packages }}"

    # enlist build essential packages if flag `build_essential` is set
    - name: Enlist build essential packages
      when: infra_build_essential_support
      set_fact: infra_packages="{{ infra_packages + infra_build_essential_packages }}"

    # enlist additional packages if provided
    - name: Enlist additional infra packages
      when: infra_additional_packages|length > 0
      set_fact: infra_packages="{{ infra_packages + infra_additional_packages }}"

    - name: Install infra packages from yum
      environment: "{{ infra_proxy_env }}"
      yum:
        disable_gpg_check: yes
        name: "{{ infra_packages }}"

...
