---
#------------------------------------------------------------------------------
# Grafana
#------------------------------------------------------------------------------
grafana_force_download_plugins: false         # force redownload grafana plugins
grafana_time_interval: 2s                     # force redownload grafana plugins
grafana_provision_via_db: true                # provision via copy sqlite db by default
grafana_dashboards: []                        # default dashboards
grafana_plugins_force_download: false         # force re-download grafana plugins ?
grafana_plugins_cache: /tmp/plugins.tar.gz    # path to grafana plugins tarball
grafana_plugins:                              # default grafana plugins list
  - redis-datasource
  - simpod-json-datasource
  - sbueringer-consul-datasource
  - camptocamp-prometheus-alertmanager-datasource
  - marcusolsson-hourly-heatmap-panel
  - michaeldmoore-multistat-panel
  - marcusolsson-treemap-panel
  - dalvany-image-panel
  - ryantxu-ajax-panel
  - cloudspout-button-panel
  - jdbranham-diagram-panel
  - grafana-piechart-panel
  - snuids-radar-panel
  - digrich-bubblechart-panel

# - reference : dcs metadata - #
dcs_type: consul                  # default dcs server type: consul
consul_check_interval: 15s        # default service check interval
consul_check_timeout:  1s         # default service check timeout
...