---
#------------------------------------------------------------------------------
# Grafana
#------------------------------------------------------------------------------
grafana_url: http://admin:admin@localhost:3000 # grafana url
grafana_admin_password: admin
grafana_plugin: install                        # none|install|reinstall
grafana_cache: /tmp/plugins.tar.gz             # path to grafana plugins tarball
grafana_provision_mode: db                     # none|db|api

grafana_plugins:                               # default grafana plugins list
  - redis-datasource
  - simpod-json-datasource
  - fifemon-graphql-datasource
  - sbueringer-consul-datasource
  - camptocamp-prometheus-alertmanager-datasource
  - ryantxu-ajax-panel
  - marcusolsson-hourly-heatmap-panel
  - michaeldmoore-multistat-panel
  - marcusolsson-treemap-panel
  - pr0ps-trackmap-panel
  - dalvany-image-panel
  - magnesium-wordcloud-panel
  - cloudspout-button-panel
  - speakyourcode-button-panel
  - jdbranham-diagram-panel
  - grafana-piechart-panel
  - snuids-radar-panel
  - digrich-bubblechart-panel

grafana_git_plugins:
  - https://github.com/Vonng/grafana-echarts

grafana_dashboards: []                        # default dashboards
...