---
#==============================================================#
# Setup pgbouncer_exporter
#==============================================================#
- name: Setup pgbouncer_exporter
  tags: pgbouncer_exporter
  block:
    - name: Config pgbouncer_exporter opts
      template: src=pgbouncer_exporter.j2 dest=/etc/default/pgbouncer_exporter owner=postgres group=postgres mode=0600

    - name: Config pgbouncer_exporter service
      copy: src=pgbouncer_exporter.service dest=/usr/lib/systemd/system/pgbouncer_exporter.service

    - name: Launch pgbouncer_exporter service
      systemd: name=pgbouncer_exporter state=restarted enabled=yes daemon_reload=yes

    - name: Wait for pgbouncer_exporter online
      wait_for: host=localhost port={{ pgbouncer_exporter_port }} state=started

    - name: Register pgb-exporter consul service
      template:
        src: svc-pgbouncer-exporter.json.j2
        dest: /etc/consul.d/svc-pgbouncer-exporter.json
        owner: consul
        group: postgres
        mode: 0660

    - name: Reload pgb-exporter consul service
      systemd: name=consul state=reloaded
...