---
#------------------------------------------------------------------------------
# Check consul
#------------------------------------------------------------------------------
- name: Check existing consul
  tags: consul_check
  block:

    - name: Check for existing consul instance
      command: 'ss -tp state listening sport = :8500'
      register: check_consul_port_result

    - name: Set consul_exists flag if exists
      set_fact:
        consul_exists: "{{ 'consul' in check_consul_port_result.stdout }}"

    - name: Abort due to existing consul instance
      when: consul_exists and dcs_exists_action == 'abort'
      any_errors_fatal: true
      fail: msg="Abort because consul instance already exists and dcs_exists_action=abort"

    - name: Skip due to existing consul instance
      when: consul_exists and dcs_exists_action == 'skip'
      meta: end_host

    - name: Clean existing consul instance
      when: consul_exists and dcs_exists_action == 'clean' # DANGEROUS!
      debug:
        msg: "[DANGEROUS] running instance {{ inventory_hostname }} will be purged!"

    # dangerous: (it will remove consul data!)
    - name: Purge existing consul instance
      script: purge_consul.sh


#------------------------------------------------------------------------------
# Config consul
#------------------------------------------------------------------------------
# dcs_servers key > pg_cluster-pg_seq > hostname
- name: Determine dcs node name
  tags: consul_config
  block:
    - name: Get dcs node name from dcs_servers dict
      connection: local
      when: inventory_hostname in dcs_servers.values()
      set_fact:
        dcs_nodename={{ (dcs_servers|dict2items|items2dict(key_name='value', value_name='key'))[inventory_hostname] }}
        dcs_role=server

    - name: Build dcs name from cluster and sequence
      when: dcs_nodename is not defined or dcs_nodename == '' and pg_cluster is defined and pg_seq is defined
      connection: local
      set_fact: dcs_nodename={{ pg_cluster }}-{{ pg_seq }}

    # fill dcs nodename with node hostname
    - name: Get hostname as consul node name
      shell: echo $HOSTNAME
      register: hostname_result

    - name: Build dcs name from cluster and sequence
      when: dcs_nodename is not defined or dcs_nodename == ''
      connection: local
      set_fact: dcs_nodename={{ hostname_result.stdout }}

    - name: Copy /etc/consul.d/consul.json
      template: src=consul.json.j2 dest=/etc/consul.d/consul.json mode=0644 owner=consul group=consul


#------------------------------------------------------------------------------
# Launch consul server first
#------------------------------------------------------------------------------
- name: Setup conul server
  tags: consul_server
  when: inventory_hostname in dcs_servers.values()
  throttle: 1                                 # setup server one by one
  block:
    # config consul
    - name: Copy consul server service unit
      template: src=consul-server.service.j2 dest=/usr/lib/systemd/system/consul.service

    # launch consul
    - name: Launch consul server service
      systemd: name=consul state=restarted enabled=yes daemon_reload=yes

    # wait consul online
    - name: Wait for consul server online
      wait_for: host=localhost port=8500 state=started timeout=30


#------------------------------------------------------------------------------
# Launch consul agent
#------------------------------------------------------------------------------
- name: Setup consul agent
  tags: consul_agent
  when: inventory_hostname not in dcs_servers.values()
  block:
    # config consul
    - name: Copy consul agent service
      copy: src=consul.service dest=/usr/lib/systemd/system/consul.service

    # launch consul
    - name: Launch consul agent service
      systemd: name=consul state=restarted enabled=yes daemon_reload=yes

    # wait consul online
    - name: Wait for consul agent online
      wait_for: host=localhost port=8500 state=started timeout=30

...
