---
#==============================================================#
# Branch 1: Setup consul
#==============================================================#
- import_tasks: consul.yml
  tags: dcs_consul
  when: dcs_type == 'consul'

#==============================================================#
# Branch 2: Setup etcd
#==============================================================#
# TODO: NOT IMPLEMENT YET
#- import_tasks: etcd.yml
#  tags: dcs_etcd
#  when: dcs_type == 'etcd'
...
