---
#------------------------------------------------------------------------------
# Prometheus
#------------------------------------------------------------------------------
prometheus_scrape_interval: 15s               # global scrape & evaluation interval
prometheus_scrape_timeout: 5s                 # scrape timeout
prometheus_metrics_path: /metrics             # default metrics path (only for job 'pg')
prometheus_data_dir: /var/lib/prometheus/data # prometheus data dir
prometheus_retention: 90d                     # how long to keep
prometheus_reload: false                      # reload prometheus instead of recreate it

# - reference : dcs metadata - #
dcs_type: consul                  # default dcs server type: consul
consul_check_interval: 15s        # default service check interval
consul_check_timeout:  1s         # default service check timeout
...