---
#------------------------------------------------------------------------------
# Install
#------------------------------------------------------------------------------
- import_tasks: install.yml
  tags: instal

#------------------------------------------------------------------------------
# Preflight
#------------------------------------------------------------------------------
# check and set inventory variables
- import_tasks: preflight.yml
  tags: preflight

#------------------------------------------------------------------------------
# Prepare
#------------------------------------------------------------------------------
# check pg existence, cleanup, create directories, copy scripts
- import_tasks: prepare.yml
  tags: prepare

#------------------------------------------------------------------------------
# postgres
#------------------------------------------------------------------------------
# bootstrap postgres cluster with patroni
- import_tasks: postgres.yml
  tags: postgres

#------------------------------------------------------------------------------
# Pgbouncer
#------------------------------------------------------------------------------
# install connection pooling middleware
- import_tasks: pgbouncer.yml
  tags: pgbouncer

#------------------------------------------------------------------------------
# Register
#------------------------------------------------------------------------------
# register postgres service
- import_tasks: register.yml
  tags: register

...