---
#------------------------------------------------------------------------------
# register postgres service
#------------------------------------------------------------------------------
- name: Register postgres service to dcs
  tags: pg_register
  block:
    - name: Copy postgres service definition
      template:
        src: svc-{{ item }}.json.j2
        dest: /etc/consul.d/svc-{{ item }}.json
        owner: consul
        group: postgres
        mode: 0660
      with_items:
        - postgres
        - pgbouncer
        - patroni

    - name: Reload consul service
      systemd: name=consul state=reloaded

    #------------------------------------------------------------------------------
    # register to grafana datasource
    #------------------------------------------------------------------------------
    # load it to data source
    - name: Create grafana datasource postgres
      when: grafana_url is defined
      ignore_errors: true
      grafana_datasource:
        name: "{{ pg_instance }}"
        grafana_url: "{{ grafana_url }}"
        grafana_user: admin
        grafana_password: "{{ grafana_admin_password | default('admin') }}"
        ds_type: postgres
        ds_url: "{{ inventory_hostname }}:5432"
        database: "{{ pg_default_database }}"
        user: "{{ pg_monitor_username }}"
        password: "{{ pg_monitor_password }}"
        sslmode: disable

...