---

- name: Install pigsty yum repo
  tags: repo_install
  ignore_errors: true
  block:
    - name: Install local yum repo
      get_url:
        url: http://{{ repo_host }}/{{ repo_name }}.repo
        dest: /etc/yum.repos.d/{{ repo_name }}.repo

    - name: Disable other yum repo
      when: repo_disable_default
      shell: |
        if [[ -f /etc/yum.repos.d/{{ repo_name }}.repo ]]; then
            yum-config-manager --disable '*'
            yum-config-manager --enable {{ repo_name }} base extras updates
        fi

...
